# =========================
# Minimal Mistakes
# =========================

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

# Site
locale: "en-US"
title: "Elizabeth (Van) Le"
description: "Data Scientist | Data Analyst | Business Intelligence Engineer"
url: "https://elizabethvanle.com"
baseurl: ""

masthead_title: ""

# Author 
author:
  name: "Elizabeth (Van) Le"
  avatar: "/assets/images/headshot.jpg" 
  bio: "Data Scientist | Analytics Engineer | BI Engineer turning data into strategic insights"
  location: "Houston, TX"
  email: "lethaovann28@gmail.com"
  links:
    - label: "Email"
      url: "mailto:lethaovann28@gmail.com"
    - label: "GitHub"
      url: "https://github.com/vanle2000/"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/elizabethvanle/"

# Build
include:
  - _pages

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README
  - tmp
  - /docs
  - /test

encoding: "utf-8"
markdown: kramdown

# URLs
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Search (optional)
search: false

# Plugins (single list only)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Defaults 
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
